language: elixir
elixir:
  - 1.6.5
otp_release:
  - 20.3.6
dist: trusty

cache:
  directories:
    - _build
    - deps

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.clean --unused
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test travis_wait mix dialyzer --plt

script:
  - mix test
  - MIX_ENV=test mix credo --strict
  - MIX_ENV=test mix dialyzer --halt-exit-status
