language: elixir
matrix:
  include:
    - elixir: "1.6.6"
      otp_release: "20.3.8.2"
    - elixir: "1.7.3"
      otp_release: "21.0.8"
dist: trusty

cache:
  directories:
    - _build
    - deps

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.clean --unused
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test travis_wait mix dialyzer --plt

script:
  - mix test
  - mix format --check-formatted
  - MIX_ENV=test mix credo --strict
  - MIX_ENV=test mix dialyzer --format short --halt-exit-status
